/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Code.*;

/**
 *
 * @author HASSAN-NAEEM
 */
public class CashierMain extends javax.swing.JFrame {

    /**
     * Creates new form CashierMain
     */
    public CashierMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel_CashierHome = new javax.swing.JLabel();
        jToggleButton_MakeSale = new javax.swing.JToggleButton();
        jToggleButton_CustomerDetails = new javax.swing.JToggleButton();
        jToggleButton_SearchReceipt = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cashier Home");
        setName("ClientHome"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 35, 53));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel_CashierHome.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_CashierHome.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        jLabel_CashierHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CashierHome.setText("Cashier Home");

        jToggleButton_MakeSale.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton_MakeSale.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jToggleButton_MakeSale.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_MakeSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart64.png"))); // NOI18N
        jToggleButton_MakeSale.setText("Make New  Sale");
        jToggleButton_MakeSale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.orange));
        jToggleButton_MakeSale.setBorderPainted(false);
        jToggleButton_MakeSale.setOpaque(true);
        jToggleButton_MakeSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_MakeSaleActionPerformed(evt);
            }
        });

        jToggleButton_CustomerDetails.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton_CustomerDetails.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jToggleButton_CustomerDetails.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_CustomerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-user.png"))); // NOI18N
        jToggleButton_CustomerDetails.setText("Update Customer");
        jToggleButton_CustomerDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.pink, java.awt.Color.white, java.awt.Color.darkGray));
        jToggleButton_CustomerDetails.setBorderPainted(false);
        jToggleButton_CustomerDetails.setOpaque(true);
        jToggleButton_CustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_CustomerDetailsActionPerformed(evt);
            }
        });

        jToggleButton_SearchReceipt.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton_SearchReceipt.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jToggleButton_SearchReceipt.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_SearchReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jToggleButton_SearchReceipt.setText("Search Receipt");
        jToggleButton_SearchReceipt.setBorderPainted(false);
        jToggleButton_SearchReceipt.setFocusPainted(false);
        jToggleButton_SearchReceipt.setOpaque(true);
        jToggleButton_SearchReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_SearchReceiptActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cashier.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jToggleButton1.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jToggleButton1.setText("Log Out");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setOpaque(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton_SearchReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton_CustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton_MakeSale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel_CashierHome, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_CashierHome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jToggleButton_MakeSale)
                .addGap(35, 35, 35)
                .addComponent(jToggleButton_CustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jToggleButton_SearchReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_MakeSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_MakeSaleActionPerformed
        // TODO add your handling code here:
        new MakeSaleUI().setVisible(true);
    }//GEN-LAST:event_jToggleButton_MakeSaleActionPerformed

    private void jToggleButton_SearchReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_SearchReceiptActionPerformed
        // TODO add your handling code here:
        new ReceiptSearch().setVisible(true);
    }//GEN-LAST:event_jToggleButton_SearchReceiptActionPerformed

    private void jToggleButton_CustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_CustomerDetailsActionPerformed
        // TODO add your handling code here:
        new UpdateCustomerUI().setVisible(true);
    }//GEN-LAST:event_jToggleButton_CustomerDetailsActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        SingletonPattern.getInstance().getSystem().getStore().setCurrentCashier(-1);
        //setVisible(false);
        this.dispose();
         
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_CashierHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton_CustomerDetails;
    private javax.swing.JToggleButton jToggleButton_MakeSale;
    private javax.swing.JToggleButton jToggleButton_SearchReceipt;
    // End of variables declaration//GEN-END:variables
}
