/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Code.*;
import java.util.*;

/**
 *
 * @author HASSAN-NAEEM
 */
public class MakeSaleUI extends javax.swing.JFrame {

    /**
     * Creates new form MakeSaleUI
     */
    DefaultTableModel model;
    public MakeSaleUI() {
        initComponents();
        model=(DefaultTableModel) jTable_MakeSale.getModel();
        
    }
    List<ItemQuantity> items = new ArrayList<ItemQuantity>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_MakeSaleTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_CustomerCNIC = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jtf_MSItemSku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jS_MSQuantity = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jb_MSAdd = new javax.swing.JToggleButton();
        jb_MSRemove = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_MakeSale = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make New Sale");
        setPreferredSize(new java.awt.Dimension(900, 665));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(1, 35, 53));

        jLabel_MakeSaleTitle.setBackground(new java.awt.Color(255, 255, 153));
        jLabel_MakeSaleTitle.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        jLabel_MakeSaleTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MakeSaleTitle.setText("Make New Sale");

        jPanel1.setBackground(new java.awt.Color(1, 35, 53));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer ID:");

        jTextField_CustomerCNIC.setText("XXXXXXXXXXX");
        jTextField_CustomerCNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CustomerCNICActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Add New Customer");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setOpaque(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item SKU:");

        jtf_MSItemSku.setText("143");
        jtf_MSItemSku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_MSItemSkuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Detail:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Details");

        jb_MSAdd.setBackground(new java.awt.Color(114, 114, 244));
        jb_MSAdd.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jb_MSAdd.setForeground(new java.awt.Color(255, 255, 255));
        jb_MSAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jb_MSAdd.setText("Add Item");
        jb_MSAdd.setBorderPainted(false);
        jb_MSAdd.setOpaque(true);
        jb_MSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MSAddActionPerformed(evt);
            }
        });

        jb_MSRemove.setBackground(new java.awt.Color(114, 114, 244));
        jb_MSRemove.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jb_MSRemove.setForeground(new java.awt.Color(255, 255, 255));
        jb_MSRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart.png"))); // NOI18N
        jb_MSRemove.setText("Remove Item");
        jb_MSRemove.setBorderPainted(false);
        jb_MSRemove.setOpaque(true);
        jb_MSRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MSRemoveActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receipt.png"))); // NOI18N
        jToggleButton2.setText("Generate Receipt");
        jToggleButton2.setBorderPainted(false);
        jToggleButton2.setOpaque(true);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(114, 114, 244));
        jToggleButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark.png"))); // NOI18N
        jToggleButton3.setText("Check");
        jToggleButton3.setBorderPainted(false);
        jToggleButton3.setOpaque(true);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jToggleButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_CustomerCNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_MSItemSku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jS_MSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jb_MSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jb_MSRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CustomerCNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_MSItemSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_MSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_MSAdd)
                    .addComponent(jb_MSRemove))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable_MakeSale.setBackground(new java.awt.Color(153, 153, 255));
        jTable_MakeSale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.red, java.awt.Color.orange, java.awt.Color.pink));
        jTable_MakeSale.setForeground(new java.awt.Color(255, 255, 255));
        jTable_MakeSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item SKU", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_MakeSale.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_MakeSale.setShowGrid(true);
        jScrollPane2.setViewportView(jTable_MakeSale);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-bag.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel_MakeSaleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_MakeSaleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_MSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MSAddActionPerformed
        // TODO add your handling code here:
        if(SingletonPattern.getInstance().getSystem().getStore().getCustomerFromCnic(jTextField_CustomerCNIC.getText())==-1){
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        }
        else{
            int itemIndex = SingletonPattern.getInstance().getSystem().getStore().getItemQuantityFromSku(jtf_MSItemSku.getText());
            float price = SingletonPattern.getInstance().getSystem().getStore().getItemQuantityList().get(itemIndex).getItem().getPrice();
            int totalQuantity = SingletonPattern.getInstance().getSystem().getStore().getItemQuantityList().get(itemIndex).getQuantity();
            int quantity = (Integer)jS_MSQuantity.getValue();
            float total=price*quantity;
            if(quantity>totalQuantity){
                JOptionPane.showMessageDialog(null, "Insufficient Quantity Available");
            }
            else{

                if(validateFields()){
                    model.insertRow(jTable_MakeSale.getRowCount(), new Object[]{
                        jtf_MSItemSku.getText() ,
                        jS_MSQuantity.getValue(),
                        total
                    });
                }
            }
            resetFields();
        }
    }//GEN-LAST:event_jb_MSAddActionPerformed

    private void jtf_MSItemSkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_MSItemSkuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtf_MSItemSkuActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jTable_MakeSale.clearSelection();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jb_MSRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MSRemoveActionPerformed
        // TODO add your handling code here:
        if(jTable_MakeSale.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(MakeSaleUI.this,"Select the Item from the Table");
            return;
        }
        model.removeRow(jTable_MakeSale.getSelectedRow());
    }//GEN-LAST:event_jb_MSRemoveActionPerformed

    private void jTextField_CustomerCNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CustomerCNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CustomerCNICActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        int customerIndex = SingletonPattern.getInstance().getSystem().getStore().getCustomerFromCnic(jTextField_CustomerCNIC.getText());
        if(customerIndex==-1){
            JOptionPane.showMessageDialog(null, "Customer does not exist");
        }
        else if (customerIndex>-1){
            JOptionPane.showMessageDialog(null, "Customer found");
        }
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(jTextField_CustomerCNIC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Specify Customer");
        }
        else if(SingletonPattern.getInstance().getSystem().getStore().getCustomerFromCnic(jTextField_CustomerCNIC.getText())==-1){
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        }
        else{
            Store store = SingletonPattern.getInstance().getSystem().getStore();
            int customerIndex = store.getCustomerFromCnic(jTextField_CustomerCNIC.getText());
            int cashierIndex = store.getCurrentCashier();
            Customer customer = store.getCustomerList().get(customerIndex);
            float categoryDiscount = customer.calculateDiscount();
            Sale sale = new Sale(store.getSaleList().size()+1, store.getCustomerList().get(customerIndex), store.getCashierList().get(cashierIndex),0);
            float totalDiscount=0;
            for(int i=0; i<jTable_MakeSale.getRowCount(); i++){
                int itemIndex = store.getItemFromSku(jTable_MakeSale.getValueAt(i, 0).toString());
                int itemQuantityIndex = store.getItemQuantityFromSku(jTable_MakeSale.getValueAt(i, 0).toString());
                
                int quantity = (Integer)jTable_MakeSale.getValueAt(i, 1);
                
                ItemQuantity item = new ItemQuantity(store.getItemL().get(itemIndex), quantity);
                sale.addItem(item);
                float discount = item.getItem().getDiscount();
                if(discount!=0){
                    totalDiscount += (discount/100 * item.getItem().getPrice()*quantity);
                    if(categoryDiscount!=0){
                         totalDiscount += (categoryDiscount/100 * item.getItem().getPrice());
                    } 
                }
                store.getItemQuantityList().get(itemQuantityIndex).decreaseQuantity(quantity);
            }
            
            
            sale.setDiscount(totalDiscount);
            SingletonPattern.getInstance().getSystem().getStore().getSaleList().add(sale);
            JOptionPane.showMessageDialog(null, "Discount: "+totalDiscount+'\n'+"Receipt id: "+sale.getSaleID());
            
            
            if(customer.gettype()==0){
                if(store.getCustomerSales(customerIndex)>=5){
                    Gold newCustomer = new Gold(customer.getAddress(), customer.getName(),customer.getCNIC(), customer.getContactNo() );
                    store.getCustomerList().set(customerIndex, newCustomer);
                     JOptionPane.showMessageDialog(null, "Customer Category Changed to Gold");
                }
            }
            else if(customer.gettype()==1){
                if(store.getCustomerSales(customerIndex)>=10){
                    Platinum newCustomer = new Platinum(customer.getAddress(), customer.getName(),customer.getCNIC() , customer.getContactNo());
                    store.getCustomerList().set(customerIndex, newCustomer);
                     JOptionPane.showMessageDialog(null, "Customer Category Changed to Platinum");
                }
            }
        }
          model.setRowCount(0);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new AddCustomer().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeSaleUI().setVisible(true);
            }
        });
        
    }
    private boolean validateFields(){
        if(jtf_MSItemSku.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(MakeSaleUI.this,"Enter Item SKU");
            jtf_MSItemSku.grabFocus();
            return false;
        }
        if((Integer)jS_MSQuantity.getValue()==0){
            JOptionPane.showMessageDialog(MakeSaleUI.this,"Specify Quantity");
            jS_MSQuantity.grabFocus();
            return false;
        }
        return true;
    }
    private void resetFields(){
        jtf_MSItemSku.setText("143");
        jS_MSQuantity.setValue(10);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_MakeSaleTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jS_MSQuantity;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_MakeSale;
    private javax.swing.JTextField jTextField_CustomerCNIC;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jb_MSAdd;
    private javax.swing.JToggleButton jb_MSRemove;
    private javax.swing.JTextField jtf_MSItemSku;
    // End of variables declaration//GEN-END:variables
}
